export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export type LOGIN_WITH_GOOGLE = typeof LOGIN_WITH_GOOGLE;